EXP_NAME: BERT
SEED: 223
    
DATASET:
    name: BERT
    data_path: ../data/Part1 # news article directory
    saved_data_path: false
    PARAMETERS:
        max_word_len: 512

TOKENIZER:
    name: bert

TRAIN:
    batch_size: 256
    num_workers: 12

RESULT:
    savedir: ../data/Part1
    dataname: 'BERT_w512'
